dist: trusty
sudo: false
language: python
python:
- '3.5'
install: pip install pelican beautifulsoup4 pelican-youtube
before_script:
- base64 -d <<< $DEPLOY_KEYS | tar -xz -C $HOME
script:
- make html
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: always
  
after_success:
- make rsync_upload
